### ISSUE TITLE
Not compilable in prod

### ISSUE THREAD

**Issue by tanguilp** [krasenyp/plug_cache_control#2]
I've got the following error when I try to compile with mix env set to `prod`:

```
== Compilation error in file lib/phoenix_http_cache_demo_web/router.ex ==
** (ArgumentError) cannot escape #Function<0.65823982/1 in PlugCacheControl.do_init/1>. The supported values are: lists, tuples, maps, atoms, numbers, bitstrings, PIDs and remote functions in the format &Mod.fun/arity
    (elixir 1.12.3) src/elixir_quote.erl:185: :elixir_quote.argument_error/1
    (elixir 1.12.3) src/elixir_quote.erl:340: :elixir_quote.do_quote/3
    (elixir 1.12.3) src/elixir_quote.erl:503: :elixir_quote.do_quote_splice/5
    (elixir 1.12.3) src/elixir_quote.erl:386: :elixir_quote.do_escape/3
    (plug 1.12.1) lib/plug/builder.ex:321: Plug.Builder.init_module_plug/4
    (plug 1.12.1) lib/plug/builder.ex:302: anonymous fn/5 in Plug.Builder.compile/3
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug 1.12.1) lib/plug/builder.ex:300: Plug.Builder.compile/3
```

I suspect this is because of https://github.com/krasenyp/plug_cache_control/blob/main/lib/plug_cache_control.ex#L84

Indeed in dev env `init/1` is compiled at runtime. See https://elixirforum.com/t/plugs-init-function-not-called-at-compile-time-in-a-phoenix-router/32206

**Comment by krasenyp** [comment]
Agh, should've thought about it. Fixed in `0.2.2`.
